#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-1 -d ">_" "</>" other 
bspc monitor DP-2 -d web telegram other

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focused_border_color "#5F8DE1"

bspc rule -a "Google-chrome" desktop=^1
bspc rule -a "Alacritty" desktop=^4
bspc rule -a "TelegramDesktop" desktop=^2 state=floating
bspc rule -a "Pavucontrol" state=floating

setxkbmap -option grp:alt_shift_toggle us,ru
feh --bg-fill ~/backgrounds/background_2.jpeg
xrandr --output HDMI-1 --auto --right-of DP-2
vibrant-cli HDMI-1 1.45
vibrant-cli DP-2 1.45
picom --experimental-backends 
